### ISSUE TITLE
Same result for different tokenizers

### ISSUE THREAD

**Issue by GRIGORR** [CAMeL-Lab/CAMeLBERT#2]
I have 680K Arabic sentences and I have used the following tokenizers to tokenize them, but they all gave the same result.
- 'CAMeL-Lab/bert-base-arabic-camelbert-mix',
- 'CAMeL-Lab/bert-base-arabic-camelbert-ca',
- 'CAMeL-Lab/bert-base-arabic-camelbert-msa',
- 'CAMeL-Lab/bert-base-arabic-camelbert-da'

I have used them by
```python
tok = AutoTokenizer.from_pretrained(tokenizer_name, force_download=True)
```
transformers version - 4.6.1

**Comment by balhafni** [comment]
That's because all of our CAMeLBERT models use the same tokenizer, which was trained on 167GB of mixed Arabic texts (i.e., MSA, DA, and CA) as described in our [paper](https://arxiv.org/pdf/2103.06678.pdf).

**Comment by GRIGORR** [comment]
I thought different models will have different tokenizers. Thanks
