### ISSUE TITLE
How many epochs for pretraining?

### ISSUE THREAD

**Issue by ghaddarAbs** [CAMeL-Lab/CAMeLBERT#3]
Hi,

Thank you for sharing your great work!!!
I was wondering for how many epochs did you pretrain CAMeLBERT? otherwise said, how many epochs the 1M steps are equivalent to?  

Thanks

**Comment by balhafni** [comment]
Thanks!! Here are the approximate number of epochs for each of our 4 CAMeLBERT models (based on the 1M steps, the batch sizes, and the number of instances within each batch):

CAMeLBERT-MIX: 2
CAMeLBERT-MSA: 6
CAMeLBERT-CA: 105
CAMeLBERT-DA: 2

**Comment by ghaddarAbs** [comment]
Thanks a lot for your answer .... I will close the issue
