### ISSUE TITLE
Question regarding pretraining task

### ISSUE THREAD

**Issue by ghaddarAbs** [CAMeL-Lab/CAMeLBERT#4]
Hi, 

I just wanted to ask if you pretrained your model on the next sentence prediction task ?

Thanks

**Comment by balhafni** [comment]
We followed the exact pretraining objectives introduced in the BERT paper. We pretrained using both MLM and NSP.

**Comment by ghaddarAbs** [comment]
Thanks, it answer my question ... I will close the issue
